# Set the build language to Python
language: minimal

jobs:
  include:
    - stage: Setup_infrastructure
    - script:
      - export VER="0.12.21"
      - wget https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
      - unzip terraform_${VER}_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - chmod +x ci-scripts/create_infrastructure.sh && ./ci-scripts/create_infrastructure.sh

    - stage: Build_docker_image
      services:
        - docker
    - script:
      - chmod +x ci-scripts/build_docker_image.sh && ./ci-scripts/build_docker_image.sh

    - stage: Deploy
      services:
        - docker
    - script:
      - export FILE_PATH="/home/travis/.docker/config.json"
      - chmod +x ci-scripts/deployment.sh && ./ci-scripts/deployment.sh
